### ISSUE TITLE
SPIKE: Figure out how to mount a directory from the host to the container

### ISSUE THREAD

**Issue by RothAndrew** [ttu-capstone-podman/choco-podman-machine-turnkey#17]
As a user of podman-machine on Windows, I want to mount a directory on my computer into the container, so that the container can see the files that are in the host folder, and the host sees any changes that the container makes to those files.

Acceptance Criteria:
1. No copying, mount only
1. 2-way mount. If I `touch somefile.txt` in the container, it shows up on the host.

**Comment by tmburks42** [comment]
It looks like you can't mount directly to the container, but you can mount to the VM and the container will be able to use it.

**Comment by RothAndrew** [comment]
Giving up on this one for now
